### ISSUE TITLE
read_liberty warning

### ISSUE THREAD

**Issue by kat54347** [abk-openroad/OpenSTA#12]
Hi James,
I got the warnings below after executing read_liberty command.

> Warning: axis type normalized_voltage not supported.
> Warning: missing variable_2 attribute.

This is the lookup table which caused the warnings

```
lu_table_template (waveform_template_name) {
 variable_1: input_net_transition;
 variable_2: normalized_voltage;
 index_1 ("float…, float");
 index_2 ("float…, float");
 }
```

This variable is supported by Liberty format but may be unused here. 
Should I just ignore the warning messages like these? Thanks!

**Comment by jjcherry56** [comment]
like it says, it is not supported.
if you depend on functionality related to that attribute it won't work.

**Comment by kat54347** [comment]
ok. Thanks!
