### ISSUE TITLE
Failure on cells such as FILL that have no pins

### ISSUE THREAD

**Issue by RTimothyEdwards** [abk-openroad/OpenSTA#2]
OpenSTA segfaults on any cell in the netlist that has no pins.
I found a fix for this that (so far) seems to work:  In VerilogReader.cc before line 930 (first line of VerilogModuleInst::namedPins()) add the following line:

   if (!pins_) return false;

That seems to keep things happy.

---Tim

**Comment by jjcherry56** [comment]
fix committed

**Comment by RTimothyEdwards** [comment]
Thank you!
