### ISSUE TITLE
Missing util/StaConfig.hh in install file list

### ISSUE THREAD

**Issue by just22** [abk-openroad/OpenSTA#21]
Hello,

trying to build a port which uses the OpenSTA API (TritonSizer), I noticed that the header file `util/StaConfig.hh` is missing in the list of files to be installed (this breaks the code in multiple places).

I solved with the following simple patch:

```
Index: CMakeLists.txt
--- CMakeLists.txt.orig
+++ CMakeLists.txt
@@ -366,6 +366,7 @@ set(STA_HEADERS
   util/ReportStd.hh
   util/ReportTcl.hh
   util/Set.hh
+  util/StaConfig.hh
   util/Stats.hh
   util/StringSeq.hh
   util/StringSet.hh
```

**Comment by jjcherry56** [comment]
looks good to me. I pushed the change to github.

**Comment by just22** [comment]
Hello James,

thanks. But now the copyright notice in `CMakeLists.txt` is the wrong one...

--
Alessandro

**Comment by jjcherry56** [comment]
ok, try again

**Comment by just22** [comment]
Thanks James, problem solved. Closing.
