### ISSUE TITLE
openSTA crashes at link_design

### ISSUE THREAD

**Issue by kunalg123** [abk-openroad/OpenSTA#3]
Hi
I am trying to run a very small design using openSTA, and looks like it crashes at link_design with segmentation fault message. Can you please have a look? 
Steps to reproduce the crash
1) Download testcase.tar.gz
2) tar -xvcf testcase.tar.gz
3) cd testcase
4) ./apps/sta -f map9v3.cmd

**Comment by jjcherry56** [comment]
where is testcase.tar.gz hiding?

**Comment by kunalg123** [comment]
Hi 
Thanks for the reply
This issue was raised 20days ago and in meantime we have fixed this issue. Would appreciate to have an early reply for issues, as we are planning to use this for real chip tapeout

**Comment by jjcherry56** [comment]
who is kunalg123?

**Comment by kunalg123** [comment]
I really apologize, as I forgot to introduce myself
My name is Kunal Ghosh and myself & Anagha Ghosh run an online company called VLSI System Design (VSD) Corp. Pvt. Ltd., primarily focused on making online content promoting open-soruce EDA tools. 
Here's my company link:
[https://www.vlsisystemdesign.com/about-us/](https://www.vlsisystemdesign.com/about-us/)

I, myself have STA and Physical design background, while Anagha has Electrical back-ground and looks into marketing, operations and strategies. Currently we are working on RISC-V based full chip tape-out using all open-source EDA tools

**Comment by jjcherry56** [comment]
I am new to github and didn't see your "issue" until two days ago. I get notifications now so new issues  won't sit for 20 days in the future.

**Comment by kunalg123** [comment]
Thank You jjcherry
Really appreciate

**Comment by jjcherry56** [comment]
If you have a testcase that causes a seg fault I would like to see it, even if you have found a work around.
