### ISSUE TITLE
set_input_transition -clock not supported

### ISSUE THREAD

**Issue by kunalg123** [abk-openroad/OpenSTA#4]
Hi 
In some of our constraints file, we have below constraint
1) set_input_transition -clock  clk -min -rise  102 [get_ports  mem_rdata_0_ ]

But instead, openSTA uses below
2) set_input_transition -min -rise  102 [get_ports  mem_rdata_0_ ]

While using 1) OpenSTA gives an error that -clock option not supported. Any reason?
We wanted to keep consistent SDC constraints across different tools for benchmarking and evaluation. Can you please let know your thoughts?

**Comment by jjcherry56** [comment]
set_input_delay -clock is supported. If you have a testcase that show otherwise you should submit it.

**Comment by jjcherry56** [comment]
Note that the title of the issue does not match the command in the body of the issue.
set_input_transition -clock is not supported. It is basically meaningless because
transition times are merged. Separate transition times are not used for each clock
in delay calculation.

**Comment by kunalg123** [comment]
Hi James
Did you had a chance to look into the syntax?
Do you want me to close this issue?

**Comment by jjcherry56** [comment]
I understand the syntax.
Using the -clock argument is meaningless with graph based delay calculation
so
it flagged as unsupported. If you omit it you will get the same result,
