### ISSUE TITLE
library keyword 'revision' interpretation error

### ISSUE THREAD

**Issue by kunalg123** [abk-openroad/OpenSTA#5]
Hi James,
In our memory libraries, we have below lines:
/* Library Documentation */
  date     : ".September xxxx"
  revision : .x.x
  comment  : "Unit Area representation == xx.xxx sq.micron" ; 

While reading these libraries, openSTA gives out below error while reading the "revision" keyword
**line 42 syntax error, unexpected $undefined, expecting FLOAT or STRING or KEYWORD or '!'.**

If I comment all above lines from library, openSTA works fine. 
Do you think, its library syntax error (as mentioned in message) or openSTA interpretation issue?

**Comment by jjcherry56** [comment]
It looks like garbage in the liberty file to me.
revision is a string attribute and your example is not enclosed in double quotes.
I would say openSTA is liberal in its parsing, which is fine but not a standard I feel required to support.

**Comment by kunalg123** [comment]
Alright
Let me inform the library team
Will close this issue for now
