### ISSUE TITLE
Predefined settings for correlation with other tool (OT)

### ISSUE THREAD

**Issue by kunalg123** [abk-openroad/OpenSTA#7]
Hi James
Currently, I am working on correlating top 10000 max and min paths from OT with openSTA for 180nm, so as to use openSTA for production chips. Do you have any predefined correlation scripts or predefined settings, which you might have used for something similar? 

PS - I am submitting this as an 'issue' as I don't see an option of a 'question' in github

**Comment by jjcherry56** [comment]
I have never used OT. The regression suite I use to verify OpenSTA is not
part of the
open source release. So no, I cannot help you.

**Comment by kunalg123** [comment]
No problems
Thanks for the reply
