### ISSUE TITLE
recognition

### ISSUE THREAD

**Issue by kunalg123** [abk-openroad/OpenSTA#9]
Hi James
I will be writing blog and submitting paper at DAC (not sure if it will be accepted, but my last year paper was accepted and had got good inflow of crowd)
My paper will be on opensta bench-marking and correlation results (with other tools), that we achieved on a major RISC-V processor using pre-layout and post-layout netlist. 
Do you mind if I put your name under acknowledgements in blog and in DAC? 
A sample is shown below:
https://www.vlsisystemdesign.com/wp-content/uploads/2017/10/conference_poster_6.pdf

**Comment by jjcherry56** [comment]
sure
